-- 코드를 작성해주세요
WITH GEN1ST AS (
    SELECT E1.ID AS PARENT, E2.ID AS CHILD1ST
    FROM ECOLI_DATA E1
    JOIN ECOLI_DATA E2
    ON (E1.ID = E2.PARENT_ID)
    WHERE E1.PARENT_ID IS NULL
),
GEN2ND AS (
    SELECT G1.PARENT, G1.CHILD1ST, E3.ID AS CHILD2ND
    FROM GEN1ST G1
    JOIN ECOLI_DATA E3
    ON (G1.CHILD1ST = E3.PARENT_ID)
)
SELECT CHILD2ND AS ID
FROM GEN2ND;