WITH PARENT AS (
    SELECT E1.ID, E2.ID AS CHILD_ID
    FROM ECOLI_DATA E1
    LEFT JOIN ECOLI_DATA E2
    ON (E1.ID = E2.PARENT_ID)
)
SELECT ID, COUNT(CHILD_ID) AS CHILD_COUNT
FROM PARENT
GROUP BY ID