/*
REST_ID 기준으로 JOIN
REST_ID, REST_NAME, FOOD_TYPE, FAVORITES ADDRESS('SEOUL') + REVIEW_SCORE(AVG) ROUND(3)
AVG(REVIEW_SCORE) DESC, FAVORITES DESC
*/
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I
JOIN REST_REVIEW R
ON (I.REST_ID = R.REST_ID)
WHERE I.TEL LIKE '02%' OR I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;